"""Study-plan authoring, storage, and evaluation.

Structured Markdown documents are the source of truth; the sessions DB holds a
derived index plus an append-only checkpoint log.  A plan is evaluated at three
points in every session that runs against it: ``start``, ``mid``, ``end``.

Shape credit: Matt Pocock's ``teach`` skill
(https://github.com/mattpocock/skills/tree/main/skills/productivity/teach) —
mission-first, learning records as ADRs, primary sources over recall.
"""

from __future__ import annotations

from .authoring import (
    INTERVIEW,
    InterviewQuestion,
    draft_plan,
    interview_spec,
    lifecycle_readiness,
    readiness,
    seed_from_history,
)
from .capabilities import (
    PLANNING_CAPABILITY_SCHEMAS,
    CapabilityRefusedError,
    PlanningCapabilityCall,
    PlanningCapabilityDispatcher,
    PlanningCapabilityName,
    PlanningCapabilityResult,
    PlanningCapabilityScope,
    normalize_planning_capability_call,
)
from .contracts import (
    ActorContext,
    AuthorityError,
    Clock,
    ConceptProposal,
    ConceptRelationProposal,
    DecideProposal,
    EvidenceValidationError,
    GoalLimitError,
    GoalProposal,
    IdGenerator,
    ImportPlanDraft,
    LifecycleError,
    LifecycleValidationError,
    MilestoneProposal,
    PlanningBrief,
    PlanningCommand,
    PlanningRequest,
    PlanningRunRef,
    PlanOutcome,
    PlanProposalDraft,
    ProposalConflictError,
    ProposalRef,
    ProposalReview,
    RecordCheckpoint,
    RecordMilestoneOutcome,
    RecordTrustedEvidence,
    SourceReference,
    SubmitProposalDraft,
    SystemClock,
    TransitionPlanStatus,
    UuidIdGenerator,
)
from .conversation_contracts import (
    PRIVACY_NOTICE,
    AttachContext,
    ConversationConflictError,
    ConversationRefusedError,
    LearnerTurn,
    OutboxEvent,
    PlanningConversationBounds,
    PlanningConversationError,
    RecoveryResult,
    TurnReceipt,
)
from .conversation_runtime import PlanningConversationRuntime
from .conversation_store import ConversationStore
from .digests import (
    compute_document_digest,
    compute_structure_digest,
    structure_projection,
)
from .evaluation import (
    CHECKPOINT_PHASES,
    ConceptEvidence,
    PlanEvaluation,
    evaluate_and_record,
    evaluate_plan,
)
from .evidence import SOURCE_TIERS, EvidenceCatalogue, tier_for_source
from .index import checkpoint_history, indexed_plans, reindex_all
from .learning_map import render_learning_map
from .lifecycle import PlanningLifecycle
from .markdown import parse_plan, render_plan
from .model_config import (
    DEFAULT_LOOPBACK_CANDIDATES,
    LoopbackCandidate,
    PlanningModelProfile,
    detect_loopback_litellm,
)
from .model_port import (
    MODEL_WIRE_VERSION,
    ArchitectPrompt,
    ModelEvent,
    ModelRequest,
    ModelTextDelta,
    ModelToolCall,
    ModelTurnCompleted,
    PlanningModelPort,
    load_architect_prompt,
)
from .models import (
    PLAN_STATUSES,
    Checkpoint,
    ConceptRef,
    ConceptRelation,
    DecisionRecord,
    EvidenceDisposition,
    EvidenceRef,
    Goal,
    LearningRecord,
    Milestone,
    Mission,
    PlanUnknown,
    Resource,
    StudyPlan,
    slugify,
)
from .multiplexer import (
    HerdrBackend,
    Multiplexer,
    TmuxBackend,
    available_backends,
    preferred_backend,
)
from .openai_compatible import (
    GatewayRequest,
    ModelProtocolError,
    OpenAICompatiblePlanningModel,
)
from .repository import (
    CommitResult,
    IdempotencyConflictError,
    MutationIntent,
    PathContainmentError,
    PlanCapacityError,
    PlanConflictError,
    PlanningPaths,
    PlanningRef,
    PlanningRepository,
    PlanningRepositoryError,
    PlanningView,
    PlanScanError,
    PlanSnapshot,
    PrivateRunArtifact,
    RecoveredIntent,
    RecoveryError,
    RecoveryReport,
)
from .scripted_model import (
    ScriptedModelError,
    ScriptedPlanningModel,
    ScriptedPreflightResult,
    ScriptedResponse,
    run_scripted_preflight,
)
from .store import (
    InvalidPlanIdError,
    PlanExistsError,
    PlanNotFoundError,
    list_plan_ids,
    list_plans,
    load_plan,
    load_plan_text,
    plan_path,
    plans_dir,
    unique_plan_id,
)

__all__ = [
    "CHECKPOINT_PHASES",
    "DEFAULT_LOOPBACK_CANDIDATES",
    "INTERVIEW",
    "MODEL_WIRE_VERSION",
    "PLANNING_CAPABILITY_SCHEMAS",
    "PLAN_STATUSES",
    "PRIVACY_NOTICE",
    "SOURCE_TIERS",
    "ActorContext",
    "ArchitectPrompt",
    "AttachContext",
    "AuthorityError",
    "CapabilityRefusedError",
    "Checkpoint",
    "Clock",
    "CommitResult",
    "ConceptEvidence",
    "ConceptProposal",
    "ConceptRef",
    "ConceptRelation",
    "ConceptRelationProposal",
    "ConversationConflictError",
    "ConversationRefusedError",
    "ConversationStore",
    "DecideProposal",
    "DecisionRecord",
    "EvidenceCatalogue",
    "EvidenceDisposition",
    "EvidenceRef",
    "EvidenceValidationError",
    "GatewayRequest",
    "Goal",
    "GoalLimitError",
    "GoalProposal",
    "HerdrBackend",
    "IdGenerator",
    "IdempotencyConflictError",
    "ImportPlanDraft",
    "InterviewQuestion",
    "InvalidPlanIdError",
    "LearnerTurn",
    "LearningRecord",
    "LifecycleError",
    "LifecycleValidationError",
    "LoopbackCandidate",
    "Milestone",
    "MilestoneProposal",
    "Mission",
    "ModelEvent",
    "ModelProtocolError",
    "ModelRequest",
    "ModelTextDelta",
    "ModelToolCall",
    "ModelTurnCompleted",
    "Multiplexer",
    "MutationIntent",
    "OpenAICompatiblePlanningModel",
    "OutboxEvent",
    "PathContainmentError",
    "PlanCapacityError",
    "PlanConflictError",
    "PlanEvaluation",
    "PlanExistsError",
    "PlanNotFoundError",
    "PlanOutcome",
    "PlanProposalDraft",
    "PlanScanError",
    "PlanSnapshot",
    "PlanUnknown",
    "PlanningBrief",
    "PlanningCapabilityCall",
    "PlanningCapabilityDispatcher",
    "PlanningCapabilityName",
    "PlanningCapabilityResult",
    "PlanningCapabilityScope",
    "PlanningCommand",
    "PlanningConversationBounds",
    "PlanningConversationError",
    "PlanningConversationRuntime",
    "PlanningLifecycle",
    "PlanningModelPort",
    "PlanningModelProfile",
    "PlanningPaths",
    "PlanningRef",
    "PlanningRepository",
    "PlanningRepositoryError",
    "PlanningRequest",
    "PlanningRunRef",
    "PlanningView",
    "PrivateRunArtifact",
    "ProposalConflictError",
    "ProposalRef",
    "ProposalReview",
    "RecordCheckpoint",
    "RecordMilestoneOutcome",
    "RecordTrustedEvidence",
    "RecoveredIntent",
    "RecoveryError",
    "RecoveryReport",
    "RecoveryResult",
    "Resource",
    "ScriptedModelError",
    "ScriptedPlanningModel",
    "ScriptedPreflightResult",
    "ScriptedResponse",
    "SourceReference",
    "StudyPlan",
    "SubmitProposalDraft",
    "SystemClock",
    "TmuxBackend",
    "TransitionPlanStatus",
    "TurnReceipt",
    "UuidIdGenerator",
    "available_backends",
    "checkpoint_history",
    "compute_document_digest",
    "compute_structure_digest",
    "detect_loopback_litellm",
    "draft_plan",
    "evaluate_and_record",
    "evaluate_plan",
    "indexed_plans",
    "interview_spec",
    "lifecycle_readiness",
    "list_plan_ids",
    "list_plans",
    "load_architect_prompt",
    "load_plan",
    "load_plan_text",
    "normalize_planning_capability_call",
    "parse_plan",
    "plan_path",
    "plans_dir",
    "preferred_backend",
    "readiness",
    "reindex_all",
    "render_learning_map",
    "render_plan",
    "run_scripted_preflight",
    "seed_from_history",
    "slugify",
    "structure_projection",
    "tier_for_source",
    "unique_plan_id",
]
