"""Self-contained flashcard and quiz JSON loader.

Reads the same JSON format generated by pdf-by-chapters from-obsidian.
No cross-package imports -- the JSON format IS the contract.

Flashcard JSON shape
--------------------
::

    {
        "title": str,          # REQUIRED -- deck/chapter display name
        "cards": [             # REQUIRED -- list of card objects
            {
                "front": str,  # REQUIRED -- question or prompt
                "back":  str   # REQUIRED -- answer or explanation
            },
            ...
        ]
    }

Files matched by glob: ``*flashcards.json``

Quiz JSON shape
---------------
::

    {
        "title": str,                  # REQUIRED -- quiz display name
        "questions": [                 # REQUIRED -- list of question objects
            {
                "question": str,       # REQUIRED -- the question text
                "hint":     str,       # optional -- hint shown on request
                "answerOptions": [     # REQUIRED -- list of option objects (>=2)
                    {
                        "text":      str,   # REQUIRED -- option display text
                        "isCorrect": bool,  # optional -- true for correct answer
                                            #             (default false)
                        "rationale": str    # optional -- explanation shown after
                                            #             answering
                    },
                    ...
                ]
            },
            ...
        ]
    }

Files matched by glob: ``*quiz.json``

Validation behaviour
--------------------
Files that fail JSON parsing or are missing required keys are skipped with a
warning logged via ``logging.getLogger(__name__)``. This keeps the loader
resilient to partial / in-progress content while giving clear diagnostics.
"""

from __future__ import annotations

import hashlib
import json
import logging
import random
from dataclasses import dataclass, field
from pathlib import Path

logger = logging.getLogger(__name__)


@dataclass
class Flashcard:
    front: str
    back: str
    source: str = ""

    @property
    def card_hash(self) -> str:
        """Stable hash for spaced repetition tracking.

        Truncated to 16 hex chars (64 bits) because:
        - Display-friendly in logs, TUI, and DB columns
        - Sufficient collision resistance for a study app (~4 billion cards
          before a 50% birthday-collision probability)
        - MUST NOT be changed: existing SM-2 spaced repetition history in
          sessions.db is keyed on this value; altering the length would
          orphan all stored review progress
        """
        return hashlib.sha256(self.front.encode()).hexdigest()[:16]


@dataclass
class QuizOption:
    text: str
    is_correct: bool
    rationale: str = ""


@dataclass
class QuizQuestion:
    question: str
    options: list[QuizOption]
    hint: str = ""
    source: str = ""

    @property
    def card_hash(self) -> str:
        """Stable hash for spaced repetition tracking.

        Truncated to 16 hex chars (64 bits) because:
        - Display-friendly in logs, TUI, and DB columns
        - Sufficient collision resistance for a study app (~4 billion cards
          before a 50% birthday-collision probability)
        - MUST NOT be changed: existing SM-2 spaced repetition history in
          sessions.db is keyed on this value; altering the length would
          orphan all stored review progress
        """
        return hashlib.sha256(self.question.encode()).hexdigest()[:16]


@dataclass
class ReviewResult:
    total: int = 0
    correct: int = 0
    incorrect: int = 0
    skipped: int = 0
    wrong_hashes: set[str] = field(default_factory=set)

    @property
    def score_pct(self) -> float:
        attempted = self.correct + self.incorrect
        return (self.correct / attempted * 100) if attempted > 0 else 0.0


def load_flashcards(directory: Path) -> list[Flashcard]:
    """Load all flashcard JSON files from a directory."""
    cards: list[Flashcard] = []
    for path in sorted(directory.glob("*flashcards.json")):
        try:
            data = json.loads(path.read_text())
        except json.JSONDecodeError as exc:
            logger.warning("Skipping %s: invalid JSON (%s)", path.name, exc)
            continue

        if not isinstance(data, dict):
            logger.warning(
                "Skipping %s: expected JSON object, got %s", path.name, type(data).__name__
            )
            continue

        if "cards" not in data:
            logger.warning("Skipping %s: missing required 'cards' key", path.name)
            continue

        if not isinstance(data["cards"], list):
            logger.warning(
                "Skipping %s: 'cards' must be a list, got %s",
                path.name,
                type(data["cards"]).__name__,
            )
            continue

        source = data.get("title", path.stem)
        for i, card in enumerate(data["cards"]):
            if not isinstance(card, dict):
                logger.warning(
                    "Skipping card %d in %s: expected object, got %s",
                    i,
                    path.name,
                    type(card).__name__,
                )
                continue
            if "front" not in card:
                logger.warning(
                    "Skipping card %d in %s: missing required 'front' field", i, path.name
                )
                continue
            if "back" not in card:
                logger.warning(
                    "Skipping card %d in %s: missing required 'back' field", i, path.name
                )
                continue
            try:
                cards.append(Flashcard(front=card["front"], back=card["back"], source=source))
            except (TypeError, ValueError) as exc:
                logger.warning("Skipping card %d in %s: %s", i, path.name, exc)
                continue

    return cards


def load_quizzes(directory: Path) -> list[QuizQuestion]:
    """Load all quiz JSON files from a directory."""
    questions: list[QuizQuestion] = []
    for path in sorted(directory.glob("*quiz.json")):
        try:
            data = json.loads(path.read_text())
        except json.JSONDecodeError as exc:
            logger.warning("Skipping %s: invalid JSON (%s)", path.name, exc)
            continue

        if not isinstance(data, dict):
            logger.warning(
                "Skipping %s: expected JSON object, got %s", path.name, type(data).__name__
            )
            continue

        if "questions" not in data:
            logger.warning("Skipping %s: missing required 'questions' key", path.name)
            continue

        if not isinstance(data["questions"], list):
            logger.warning(
                "Skipping %s: 'questions' must be a list, got %s",
                path.name,
                type(data["questions"]).__name__,
            )
            continue

        source = data.get("title", path.stem)
        for i, q in enumerate(data["questions"]):
            if not isinstance(q, dict):
                logger.warning(
                    "Skipping question %d in %s: expected object, got %s",
                    i,
                    path.name,
                    type(q).__name__,
                )
                continue
            if "question" not in q:
                logger.warning(
                    "Skipping question %d in %s: missing required 'question' field", i, path.name
                )
                continue

            answer_options = q.get("answerOptions", [])
            if not isinstance(answer_options, list):
                logger.warning(
                    "Skipping question %d in %s: 'answerOptions' must be a list, got %s",
                    i,
                    path.name,
                    type(answer_options).__name__,
                )
                continue

            options: list[QuizOption] = []
            for j, opt in enumerate(answer_options):
                if not isinstance(opt, dict):
                    logger.warning(
                        "Skipping option %d of question %d in %s: expected object, got %s",
                        j,
                        i,
                        path.name,
                        type(opt).__name__,
                    )
                    continue
                if "text" not in opt:
                    logger.warning(
                        "Skipping option %d of question %d in %s: missing required 'text' field",
                        j,
                        i,
                        path.name,
                    )
                    continue
                options.append(
                    QuizOption(
                        text=opt["text"],
                        is_correct=opt.get("isCorrect", False),
                        rationale=opt.get("rationale", ""),
                    )
                )

            try:
                questions.append(
                    QuizQuestion(
                        question=q["question"],
                        options=options,
                        hint=q.get("hint", ""),
                        source=source,
                    )
                )
            except (TypeError, ValueError) as exc:
                logger.warning("Skipping question %d in %s: %s", i, path.name, exc)
                continue

    return questions


_GENERIC_DIR_NAMES = {"downloads", "content", "data", "files", "output", "generated"}

# Course-internal subdirs created by storage.get_course_dir. These are NEVER
# courses themselves — a ``flashcards/`` dir contains ``*flashcards.json`` which
# would otherwise match _has_review_content and surface as a bogus "flashcards"
# course. Discovery must never recurse into or report these.
_DECK_SUBDIRS = frozenset(
    {"flashcards", "quizzes", "audio", "chapters", "video", "slides"}
)

# Depth guard for the recursive course search. The real vault is
# ``base/<publisher>/<course>/`` (3 levels); 4 leaves headroom without risking
# a runaway walk of an arbitrarily deep tree.
_MAX_DISCOVERY_DEPTH = 4


def _course_name(directory: Path) -> str:
    """Derive a display name from a directory path.

    Uses the parent name when the directory has a generic name like 'downloads'.
    """
    name = directory.name
    if name.lower() in _GENERIC_DIR_NAMES:
        return directory.parent.name
    return name


def discover_directories(config_dirs: list[str] | None = None) -> list[tuple[str, Path]]:
    """Discover course directories with flashcard/quiz content.

    Returns list of (course_name, directory_path) tuples.

    The real study vault is a 3-level tree --
    ``base/<publisher>/<course>/{flashcards,quizzes}/`` -- so a flat
    "base + one child level" scan never reached the course dirs that
    ``content.job`` writes to (the publisher level is one hop too shallow).
    Discovery therefore walks down to ``_MAX_DISCOVERY_DEPTH``, stopping at the
    FIRST content-bearing directory on each branch (a course is a leaf: we must
    not descend into its ``flashcards/`` deck subdir and report that as a
    second, bogus course).

    The legacy ``downloads/`` special-case is preserved for flat vaults.
    """
    if not config_dirs:
        return []

    courses: list[tuple[str, Path]] = []
    seen: set[Path] = set()
    for dir_str in config_dirs:
        base = Path(dir_str).expanduser()
        if not base.is_dir():
            continue

        # Check if this directory itself has content (flat single-course layout).
        if _has_review_content(base):
            _append_course(courses, seen, _course_name(base), base)
            continue

        # Legacy: a downloads/ holding the decks directly under the root.
        downloads = base / "downloads"
        if downloads.is_dir() and _has_review_content(downloads):
            _append_course(courses, seen, _course_name(base), downloads)
            continue

        # Otherwise descend the publisher/course tree.
        _discover_recursive(base, courses, seen, depth=0)

    return courses


def _discover_recursive(
    directory: Path,
    courses: list[tuple[str, Path]],
    seen: set[Path],
    depth: int,
) -> None:
    """Walk ``directory``'s children, collecting content-bearing course dirs.

    A content-bearing directory is treated as a leaf course -- recursion stops
    there so its ``flashcards/`` / ``quizzes/`` deck subdirs are never reported
    as their own courses. Deck subdirs and dot-dirs are skipped entirely.
    """
    if depth >= _MAX_DISCOVERY_DEPTH:
        return
    for child in sorted(directory.iterdir()):
        if not child.is_dir() or child.name.startswith("."):
            continue
        if child.name in _DECK_SUBDIRS:
            continue
        if _has_review_content(child):
            _append_course(courses, seen, _course_name(child), child)
            continue
        _discover_recursive(child, courses, seen, depth + 1)


def _append_course(
    courses: list[tuple[str, Path]],
    seen: set[Path],
    name: str,
    path: Path,
) -> None:
    """Append (name, path) once, de-duplicating on the resolved path."""
    resolved = path.resolve()
    if resolved in seen:
        return
    seen.add(resolved)
    courses.append((name, path))


def _has_review_content(directory: Path) -> bool:
    """Check if a directory has flashcard or quiz JSON files."""
    fc_dir = directory / "flashcards"
    quiz_dir = directory / "quizzes"

    if fc_dir.is_dir() and list(fc_dir.glob("*flashcards.json")):
        return True
    if quiz_dir.is_dir() and list(quiz_dir.glob("*quiz.json")):
        return True
    if list(directory.glob("*flashcards.json")):
        return True
    return bool(list(directory.glob("*quiz.json")))


def find_content_dirs(directory: Path) -> tuple[Path | None, Path | None]:
    """Find flashcard and quiz subdirectories within a directory."""
    fc_dir: Path | None = None
    quiz_dir: Path | None = None

    fc_sub = directory / "flashcards"
    if fc_sub.is_dir() and list(fc_sub.glob("*-flashcards.json")):
        fc_dir = fc_sub
    elif list(directory.glob("*flashcards.json")):
        fc_dir = directory

    quiz_sub = directory / "quizzes"
    if quiz_sub.is_dir() and list(quiz_sub.glob("*-quiz.json")):
        quiz_dir = quiz_sub
    elif list(directory.glob("*quiz.json")):
        quiz_dir = directory

    return fc_dir, quiz_dir


def shuffle_items(items: list, enabled: bool = True) -> list:
    """Shuffle a list if enabled."""
    if enabled:
        result = list(items)
        random.shuffle(result)
        return result
    return items
